projects:
  Bulletin Board:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: yegko6iwpvfyjpuespnzkynlnu
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-2
      endpoints:
        prod: >-
          https://feuw67bn7fh2zp4wt6zfseqwba.appsync-api.us-east-2.amazonaws.com/graphql
